<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<UseWindowsForms>true</UseWindowsForms>
		<ImplicitUsings>enable</ImplicitUsings>
		<GeneratePackageOnBuild>False</GeneratePackageOnBuild>
		<Title>DataGridViewLaitra</Title>
	</PropertyGroup>
	<ItemGroup>
	  <PackageReference Include="Laitra.DataGridView" Version="1.0.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\DataGridView.Services.Contracts\DataGridView.Services.Contracts.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Forms\MainForm.cs">
			<SubType>Form</SubType>
		</Compile>
		<Compile Update="Forms\TourForm.cs">
			<SubType>Form</SubType>
		</Compile>
	</ItemGroup>
</Project>